Attribute VB_Name = "vars"
Public MoveWindow As Boolean
Public UseDefault As Boolean
Public CurrentUser As String
Public ShadowMode As Integer
Public TimerReset As Integer
Public Fatmode As Integer
Public DlgType As Integer
Public XMouse As Integer
Public YMouse As Integer
'Public WLeft As Integer
'Public WTop As Integer
Public Creg As Integer
