Attribute VB_Name = "vars"
Public EnableAnimations As Boolean
Public TrueOrFalse As Boolean
Public WinDesign As Integer
Public Mheight As Integer
Public Mwidth As Integer
Public RegAnimation As String
Public ChadShadow As String
Public MoveWin As String
Public InsPath As String
Public TType As String
