Attribute VB_Name = "vars"
Public DlgType As Integer
Public ShadowMode As Integer
Public CurrentUser As String
'Public WLeft As Integer
'Public WTop As Integer
Public TimerReset As Integer
Public Fatmode As Integer
Public Creg As Integer
Public XMouse As Integer
Public YMouse As Integer
